cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',views.cart_detail,name='cart_detail'),

    url(r'^add/(?P<product_id>\d+)/$',
                     views.cart_add,
                     name='cart_add'),

    url(r'^remove/(?P<product_id>\d+)/$',
                    views.cart_remove,
                    name='cart_remove'),                 

]

myshop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
url(r'^create/$',views.order_create,
                name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from .  import views

urlpatterns = [
    url(r'^$',views.product_list,name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
       views.product_detail,
       name='product_detail'),   
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.shortcuts import render
from django.db import models
from shop.models import Product


class Order(models.Model):
    """
    Order model
    """
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Ordering {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    """
    OrderItem
    """
    order = models.ForeignKey(Order,
                              related_name='items')
    product = models.ForeignKey(Product,
                                related_name='order_items')   
    price = models.DecimalField(max_digits=10,decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity
            

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
    """
    Category model
    """
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                           db_index=True,
                           unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'  

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    """
    Product model
    """   
    category = models.ForeignKey(Category,
                                related_name='products')
    name  = models.CharField(max_length=200,
                             db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name  

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id,self.slug])                                                                                                                                 

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,12)]

class CartAddProductForm(forms.Form):
    """
    CartAddProductForm
    """

    quantity = forms.TypedChoiceField(
                                    choices=PRODUCT_QUANTITY_CHOICES,
                                    coerce=int)
    update = forms.BooleanField(required=False,
                               initial=False,
                               widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.Form):
    class Meta:
        model = Order
        fields = ['first_name','late_name','email','address',
                    'postal_code','city']

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request,product_id):
    """
    Add product(s) to  cart
    """
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = cleaned_data
        cart.add(product=product,
                quantity=cd['quantity'],
                update_quantity=cd['update'])
    return redirect('cart:cart_detail') 

def cart_remove(request,product_id):
    """
    cart_remove
    """
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')    

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity':item['quantity'],
            'update':True})
    return render(request,'cart/detail.html',{'cart':cart})               

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                        product=item['product'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            cart.clear()    
        return render(request,'orders/order/create.html',
                               {'order':order})
    else:
        form = OrderCreateForm()
    return render(request,'orders/order/create.html',
                           {'cart':cart,'form':form})                                                           

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request,category_slug=None):
    """
    product_list view
    """
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
        products = products.filter(category=category)
    return render(request,'shop/product/list.html',
                           {'category':category,
                           'categories':categories,
                           'products':products})  

def product_detail(request,id,slug):
    """
    product_detail
    """ 
    product = get_object_or_404(Product,
                               id=id,
                               slug=slug,
                               available=True)
    cart_product_form = CartAddProductForm()                           
    return render(request,
                 'shop/product/detail.html',
                 {'product':product,
                 'cart_product_form':cart_product_form})  

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
<thead>
<tr>
<th>Image</th>
<th>Product</th>
<th>Quantity</th>
<th>Remove</th>
<th>Unit price</th>
<th>Price</th>
</tr>
</thead>
<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
<td>
<a href="{{ product.get_absolute_url }}">
<img src="{% if product.image %}{{ product.image.url
}}{% else %}{% static "img/no_image.png" %}{% endif %}">
</a>
</td>
<td>{{ product.name }}</td>
<td>
        <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ item.update_quantity_form.quantity }}
        {{ item.update_quantity_form.update }}
        <input type="submit" value="Update">
        {% csrf_token %}
        </form>
        </td>
<td><a href="{% url "cart:cart_remove" product.id
%}">Remove</a></td>
<td class="num">${{ item.price }}</td>
<td class="num">${{ item.total_price }}</td>
</tr>
{% endwith %}
{% endfor %}
<tr class="total">
<td>Total</td>
<td colspan="4"></td>
<td class="num">${{ cart.get_total_price }}</td>
</tr>
</tbody>
</table>
<p class="text-right">
<a href="{% url "shop:product_list" %}" class="buttonlight">Continue shopping</a>
<a href="{% url "orders:order_create" %}" class="button">Checkout</a>
</p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}
Checkout
{% endblock %}
{% block content %}
<h1>Checkout</h1>
<div class="order-info">
<h3>Your order</h3>
<ul>
{% for item in cart %}
<li>
{{ item.quantity }}x {{ item.product.name }}
<span>${{ item.total_price }}</span>
</li>
{% endfor %}
</ul>
<p>Total: ${{ cart.get_total_price }}</p>
</div>
<form action="." method="post" class="order-form">
{{ form.as_p }}
<p><input type="submit" value="Place order"></p>
{% csrf_token %}
</form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}
Thank you
{% endblock %}
{% block content %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is
<strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}My shop{% endblock %}</title>
<link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
<a href="/" class="logo">My shop</a>
</div>
<div id="subheader">
        <div class="cart">
                {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                Your cart:
                <a href="{% url "cart:cart_detail" %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}
                </div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
<p class="price">${{ product.price }}</p>
<form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
{{ product.description|linebreaks }}
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Categories</h3>
<ul>
    <li {% if not category %}class="selected"{% endif %}>
    <a href="{% url "shop:product_list" %}">All</a>
    </li>
    {% for c in categories %}
    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
    </li>
    {% endfor %}
    </ul>
    </div>
    <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif  %}</h1>
    {% for product in products %}
    <div class="item">
    <a href="{{ product.get_absolute_url }}">
    <img src="{% if product.image %}{{ product.image.url }}{%
    else %}{% static "img/no_image.png" %}{% endif %}">
    </a>
    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
    ${{ product.price }}
    </div>
    {% endfor %}
    </div>
    {% endblock %}